### ISSUE TITLE
codesquad-members-2022/airbnb#42 리뷰 피드백 반영

### ISSUE THREAD

**Issue by astraum** [ios-h/airbnb#12]
### 💡  Issue
codesquad-members-2022/airbnb#42 리뷰 피드백 반영

### 💻  작업 내용
- [x] ID 생성전략을 IDENTITY로 명시
- [x] fetchType을 LAZY로 명시
- [x] AccommodationType enum 생성
- [x] accommodation 테이블 DDL에서 city, country, gu 칼럼을 address로 합치고 적절한 VARCHAR 길이 할당
- [x] Spring boot 버젼 2.7.0(0번대는 마이너 버젼) 에서 2.6.6으로 변경

**Comment by mybloom** [comment]
### 리뷰내용을 토대로 유의하면서 개발 해야 할 사항
1. api 설계 get 요청시 모든 조건들 쿼리 파라미터로 개발
2. JPA 객체 클래스의 기본 생성자가 public 또는 protected라는 제약.
모든 생성자 필요한지 확인하면서 개발(굳이 객체 생성 단계에서 모든 프로퍼티를 오픈해놓는 방식으로 생성자를 구현할 필요는 없다고 생각합니다.)


### 1차 리뷰 추가 확인해야 할 사항
1. 시간이 되시면 이 지점에 대해서도 한번 고민해보시면 좋겠습니다.
왜 객체 클래스에는 기본 생성자가 필수인 것일까요. 꼭 필수여야 만 하는 이유가 있을까요. 등등등...

2. JPA와 MySQL을 사용하여 지역 데이터를 다루는 경험을 하시게 되겠네요.
JPA에서는 Spatial Type을 사용하기 위한 hibernate-spatial 라이브러리가 있으니 참고하시기 바래요
https://kwonnam.pe.kr/wiki/java/hibernate/spatial

3. application.yml:  향후 공간정보 쿼리를 사용하려면 MySQL56InnoDBSpatialDialect 를 명시하셔야 하겠군요.
